spring:
  application:
    name: update_timeout_application
camunda:
  client:
    mode: self-managed
    auth:
      client-id: zeebe
      client-secret: zecret
      issuer: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
    zeebe:
      enabled: true
      grpc-address: http://localhost:26500
      rest-address: http://localhost:8088
      
zeebe.initial-timeout: 30000
zeebe.timeout-threshold: 5000